### ISSUE TITLE
Homing for Stage A on the X10 is backwards

### ISSUE THREAD

**Issue by dlwalter** [Kurokesu/SCF4-SDK#15]
[gui_L054(for C1_PRO_X10 camera)/hw_serial.cpp](https://github.com/Kurokesu/SCF4-SDK/blob/0569f7063358c965ff743d2786ba79390e01b9fa/src/gui_L054%20(for%20C1_PRO_X10%20camera)/hw_serial.py#L170) contains the following code for homing the first stage:

```
if rec == "seek_a":                            
    status_str = self.__ser_send(ser, "!1") 
    status = self.__parse_status(status_str)
    if status[3] == 1: 
        self.__ser_send(ser, "G91")
        self.__ser_send(ser, "M231 A")          # Set motion to forced mode
        self.__ser_send(ser, "G0 A+100") 
        self.__wait_till_stop(ser, status[CHA_PI], CHA_PI)     # Wait until homing is over 
    else: 
        self.__ser_send(ser, "G91") 
        self.__ser_send(ser, "M231 A")          # Set motion to forced mode
        self.__ser_send(ser, "G0 A-100") 
        self.__wait_till_stop(ser, status[CHA_PI], CHA_PI)     # Wait until homing is over
```

which results in incorrect homing behavior.  Stage A moves away from the center reference point.  The G0 command should be reverse for each case.

```
if rec == "seek_a":                            
    status_str = self.__ser_send(ser, "!1") 
    status = self.__parse_status(status_str)
    if status[3] == 1: 
        self.__ser_send(ser, "G91")
        self.__ser_send(ser, "M231 A")          # Set motion to forced mode
        self.__ser_send(ser, "G0 A-100")      # <--reverse direction
        self.__wait_till_stop(ser, status[CHA_PI], CHA_PI)     # Wait until homing is over 
    else: 
        self.__ser_send(ser, "G91") 
        self.__ser_send(ser, "M231 A")          # Set motion to forced mode
        self.__ser_send(ser, "G0 A+100")      # <--reverse direction 
        self.__wait_till_stop(ser, status[CHA_PI], CHA_PI)     # Wait until homing is over
```

Results in correct homing behavior.

**Comment by Lukse** [comment]
Actually original version is correct (checked on with actual hardware). Some lenses have slightly different wiring. But thank you for insights!

**Comment by dlwalter** [comment]
> Some lenses have slightly different wiring

Does this mean if I purchase another x10 it could be wired backwards and require a different algorithm to home?

**Comment by Lukse** [comment]
All same type lenses should behave the same. Do you have camera serial number?

**Comment by dlwalter** [comment]
Model: C1 PRO X10
Serial: 000014

**Comment by Lukse** [comment]
Thank you! Turns out I did not commit final source code to Github and was testing development code. Will go through all sources and commit latest code later today.
