### ISSUE TITLE
Documentation shows conflicting descriptions for G90 and G91 codes

### ISSUE THREAD

**Issue by dlwalter** [Kurokesu/SCF4-SDK#16]
https://wiki.kurokesu.com/books/scf4/page/controlling-scf4-with-g-code-commands

This page initially describes

G90 - Absolute Programming Mode
G91 - Incremental Programming Mode

then later on the page describes

G90 - Relative coordinates
Switch to relative coordinate programming mode. Motors can be instructed to turn positive or negative 0 ~ 65535 steps (16-bits). When the counter exceeds this range, it will overflow. And will not affect motor movement.

G91 - Absolute coordinates  
Switch to absolute coordinate programming mode. In this mode, the range is limited by the internal 16-bit motor register and can be operated in a range of 0 ~ 65535.

G90 should be Absolute Coordinates and G91 should be Relative Coordinates.  Or Incremental to keep with the initial language.

**Comment by Lukse** [comment]
Thank you for noticing! Mistype in general description. G90 is absolute coordinate system. Fixed now.
